---
sidebar: sidebar
permalink: task_configure_data_collectors.html
keywords: acquisition, AU, data collector, collector
summary: Configure data collectors
---

= Configuring Data Collectors


[.lead]
You configure Data Collectors in your Cloud Insights environment to collect data from devices in the data center.

=== Configuring a New Data Collector

.Before you begin

* You must have Account owner or Admin privileges to configure data collectors. 
* You must have configured an Acquisition Unit before you can start collecting data.
* You need credentials for the devices from which you are collecting data.
+
Device network addresses, account information, and passwords are required for all devices you are collecting data from.

.Steps
. From the Cloud Insights menu, click *Admin > Data Collectors*
+
The system displays the available Data Collectors arranged by vendor.

. Click *+ Collector* on the required vendor and select the data collector to configure.
+
In the dialog box you can configure the data collector and add an Acquisition Unit.

. Enter a name for the data collector. Names can contain the following characters:

* letter (a-z)
* number (0-9)
* hyphen (-)
* underscore (_)
* period (.)
* space ( )
+

Names may not begin or end with a space, period, or hyphen.

. Enter the Acquisition Unit to associate with this data collector.
. Enter the required fields in the Configuration screen.
. Click *Advanced Configuration* to add additional configuration fields. (Not all data collectors require advanced configuration.)
. Click *Test Configuration* to verify that the data collector is properly configured.

For help adding a new Acquisition Unit, see link:task_configure_acquisition_unit.html[Configuring acquisition units]

=== Moving a Data Collector to a Different Acquisition Unit

To move a data collector to a different acquisition unit, do the following:

. If you have not already done so, Add the new link:task_configure_acquisition_unit.html[Acquisition Unit].
. From *Admin > Data Collectors*, click on the Options menu to the right of the data collector you 

